workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.example.phone_auth_app"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - alexandr.kim.1990@gmail.com
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
        track: internal
        changes_not_sent_for_review: true

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_credentials
      vars:
        BUNDLE_ID: "com.example.phoneAuthApp"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - alexandr.kim.1990@gmail.com

  web-workflow:
    name: Web Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_credentials
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - alexandr.kim.1990@gmail.com

variable_groups:
  - name: google_credentials
    variables:
      - key: GOOGLE_PLAY_CREDENTIALS
        value: $GOOGLE_PLAY_CREDENTIALS
        group: google_credentials 